### ISSUE TITLE
CodeClimate action for Python (conda) does not work

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [paambaati/codeclimate-action#110]
I think similar to https://github.com/paambaati/codeclimate-action/issues/109 where it doesn't work for GoLang, it also doesn't work for Python coverage:

```yml
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CodeClimate }}
      with:
        coverageCommand: coverage run -m unittest discover test
        debug: true

```

Results in:
```
./cc-reporter before-build
coverage run -m unittest discover test
##[error]Error: There was an error when attempting to execute the process 'coverage'. This may indicate the process failed to start. Error: spawn coverage ENOENT
##[error]🚨 Coverage run failed!
(node:4858) UnhandledPromiseRejectionWarning: Error: There was an error when attempting to execute the process 'coverage'. This may indicate the process failed to start. Error: spawn coverage ENOENT
    at ExecState._setResult (/home/runner/work/_actions/paambaati/codeclimate-action/v2.4.0/node_modules/@actions/exec/lib/toolrunner.js:545:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/paambaati/codeclimate-action/v2.4.0/node_modules/@actions/exec/lib/toolrunner.js:531:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v2.4.0/node_modules/@actions/exec/lib/toolrunner.js:418:27)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:4858) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4858) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Maarten-vd-Sande** [comment]
I think the problem is that I am making use of conda as environment management, and coverage.py is installed there. Conda is a bit finicky, and needs to be initialized. This initialization is not carried along between steps, so that means coverage can not be found.

https://github.com/actions/starter-workflows/issues/44

Somehow I can not pass multiple Commands to coverageCommand:

`conda init powershell; conda activate environment; coverage run -m ...`

As this is interpreted as a single command by `exec`.

Possible solutions:
- Is it possible to split these so that exec sees them as separate commands? I wasn't able to find out how.
- Accept a shell command. I am not entirely sure how different shells work. It seems that powershell should work with conda. There is a WIP that supports different shells: https://github.com/actions/toolkit/pull/285

**Comment by paambaati** [comment]
@Maarten-vd-Sande I'd rather wait for https://github.com/actions/toolkit/pull/285 to land before attempting to solve this problem.

> Is it possible to split these so that exec sees them as separate commands?

Technically possible but escaping delimiters, especially in a shell context, can be tricky because most of them already mean something in shells.

**Comment by Maarten-vd-Sande** [comment]
I understand. Currently I solved it by switching to pip instead of conda and it works just as well, so for me personally there is no hurry.

**Comment by paambaati** [comment]
Sounds good, I’ll close this for now then.

**Comment by geshan** [comment]
how did you solve it @Maarten-vd-Sande ?

**Comment by Maarten-vd-Sande** [comment]
@geshan I "solved" it by just not using conda, but by using pip. Pip is the "standard" package manager for python. Something like this works for me:

```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies 🔨
      run: |
        python -m pip install --upgrade pip
        pip install [the stuff I want to install]

    - name: Run tests
      run: |
        coverage run -m unittest discover -v test

    - uses: paambaati/codeclimate-action@v2.5.3
      if: always()
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CodeClimate }}
      with:
        coverageCommand: coverage xml
```
