### ISSUE TITLE
action don't run the coverageCommand

### ISSUE THREAD

**Issue by lielran** [paambaati/codeclimate-action#237]
**Describe the bug**
I tried to use the action but it seems not running the `command` 
the debug flag also doesn't show any more details 

**Version of `codeclimate-action` you're using**
`v2.7.1`

here is the usage part from my workflow file:
```
      - name: ✅ Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.1
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageCommand: yarn test:unit-coverage

```
the running result:
![Screen Shot 2020-10-01 at 8 45 32](https://user-images.githubusercontent.com/1004667/94772528-808a0600-03c2-11eb-9973-b06edf6de312.png)
