### ISSUE TITLE
Getting UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dahliacreative** [paambaati/codeclimate-action#344]
I've tried setting up following the examples however I get this error and no reports are sent to CC:
```
(node:2154) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Function.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/glob/lib/internal-globber.js:160:36)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/glob/lib/internal-globber.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/glob/lib/internal-globber.js:4:12)
    at Function.create (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/glob/lib/internal-globber.js:154:16)
    at Object.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/glob/lib/glob.js:21:56)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/paambaati/codeclimate-action/v2.7.5/node_modules/@actions/glob/lib/glob.js:8:71
    at new Promise (<anonymous>)
(node:2154) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2154) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Version of `codeclimate-action` you're using**
`v2.5.7`

My setup is quite straightforward so not sure what is happening:
```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - run: npm install
      - run: npm build
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TOKEN }}
        with:
          coverageCommand: npm run test:ci:unit
          coverageLocations: ${{github.workspace}}/coverage/lcov.info
  ```
Any help, greatly appreciated!
