### ISSUE TITLE
Failed job `fatal: unsafe repository ('/__w/T-Regx/T-Regx' is owned by someone else)`

### ISSUE THREAD

**Issue by Danon** [paambaati/codeclimate-action#536]
**Describe the bug**

Action fails with a vanilla configuration, my configuration looks like this, I think it's pretty standard.

```yaml
- name: Upload coverage results to Code Climate
  if: "${{ matrix.coverage != 'none' }}"
  uses: paambaati/codeclimate-action@v3.0.0
  continue-on-error: true
  env:
    CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
```

**Version of `codeclimate-action` you're using**
`v3.0.0`

**Example links**
1. Example build run with `debug: true`: https://github.com/T-Regx/T-Regx/runs/6261918186?check_suite_focus=true
2. Workflow config: https://github.com/T-Regx/T-Regx/blob/master/.github/workflows/build.yaml

**Expected behavior**

The action uploads coverage to code climate.
