### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by Synertry** [paambaati/codeclimate-action#630]
**Describe the bug**
The action errors after generating the coverage with:
```bash
/home/runner/work/_actions/paambaati/codeclimate-action/v3.2.0/node_modules/@actions/glob/lib/internal-globber.js:173
            const lines = patterns.split('\n').map(x => x.trim());
                                   ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Function.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v3.2.0/node_modules/@actions/glob/lib/internal-globber.js:173:36)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/paambaati/codeclimate-action/v3.2.0/node_modules/@actions/glob/lib/internal-globber.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/paambaati/codeclimate-action/v3.2.0/node_modules/@actions/glob/lib/internal-globber.js:23:12)
    at Function.create (/home/runner/work/_actions/paambaati/codeclimate-action/v3.2.0/node_modules/@actions/glob/lib/internal-globber.js:167:16)
    at Object.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v3.2.0/node_modules/@actions/glob/lib/glob.js:23:56)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/paambaati/codeclimate-action/v3.2.0/node_modules/@actions/glob/lib/glob.js:8:71
    at new Promise (<anonymous>)
```

**Version of `codeclimate-action` you're using**
`v3.2.0`

**Example links**
1. Configure your job to include the [`debug: true`](https://github.com/paambaati/codeclimate-action#inputs) flag and the [`ACTIONS_STEP_DEBUG` secret to `true`](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs) so I can get additional debugging information.
Both enabled, but enabling ACTIONS_STEP_DEBUG secret does not show more useful info at all.

2. Include links to the specific Github action run and your config.
[https://github.com/Synertry/RushDevsDailyGo/actions/runs/3307664720/jobs/5459463366](https://github.com/Synertry/RushDevsDailyGo/actions/runs/3307664720/jobs/5459463366)

**Expected behavior**
Finishing the step by uploading the coverage without errors

**Additional context**
Step configuration:
```yaml
      - name: Generate Code Coverage & report to Codeclimate
        if: needs.precheck.outputs.doc_only != 'true'
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: go test -v -race -vet off -covermode atomic -coverprofile coverage.out ./Daily/...
          coverageLocations: |
            coverage.out
          debug: true
```
