### ISSUE TITLE
GithubActions: couldn't load committed at from ENV, trying git..

### ISSUE THREAD

**Issue by David-Trejo** [paambaati/codeclimate-action#633]
**Describe the bug**
I am unable to get code coverage reports published onto CodeClimate. I was able to fix the formatter issue that was ocurring, but now experience this issue of `couldn't load committed at from ENV, trying git..`. I've attached a picture of the logs from GithubActions. Any solutions to be able to get it to work? 

I've tried downgrading the library to 2.7.0 with the simplest configuration. It sucesfully passes but doesn't publish the code coverage reports to CodeClimate. 

**Version of `codeclimate-action` you're using**
`v3.2.0`

**Example links**
1. Configure your job to include the [`debug: true`](https://github.com/paambaati/codeclimate-action#inputs) flag and the [`ACTIONS_STEP_DEBUG` secret to `true`](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs) so I can get additional debugging information.
2. Include links to the specific Github action run and your config.
![Screen Shot 2022-11-01 at 1 55 36 PM](https://user-images.githubusercontent.com/30052753/199315374-8d10a32f-e414-4c3b-b75a-1232d1088d9f.png)

Configuration: 

```yaml
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ github.secret.cc_test_reporter_id }}
        with:
          coverageCommand: make test-titan-ivr-campaigns
          debug: true
          coverageLocations: |
            /home/runner/work/Titan/Titan/applications/react/modern/ivr-campaigns/coverage/lcov.info:lcov
```

**Expected behavior**
Publish code coverage reports to CodeClimate. 

**Additional context**
