### ISSUE TITLE
Detected dubious ownership in repository

### ISSUE THREAD

**Issue by marcospassos** [paambaati/codeclimate-action#654]
**Describe the bug**
I started seeing this error today:
![image](https://user-images.githubusercontent.com/943036/223167915-e9a2de78-899a-4f76-adb2-18218998b3dc.png)

**Version of `codeclimate-action` you're using**
`v3.2.0`

**Expected behavior**
Not error.

**Config**:
```yml
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TESTREPORTER_ID }}
        with:
          coverageCommand: sed -i "s~$(pwd)/~~" phpunit-coverage.xml
          coverageLocations: ./phpunit-coverage.xml:clover
```

**Comment by paambaati** [comment]
Related – https://github.com/actions/runner-images/issues/6775

This seems to be caused by old (or perhaps mismatched) versions of the runner. There are conflicting reports so it is unclear (for now) what the exact root cause is.

**Comment by paambaati** [comment]
@marcospassos What OS and runner version is your action using?

**Comment by marcospassos** [comment]
We have, right now, 100+ packages failing due to this. It's only affecting the `codeclimate-action` action, so I believe it should have something related to it.

**Comment by paambaati** [comment]
@marcospassos If this is a blocker, I would recommend removing the action temporarily, as I'm not seeing this elsewhere (including personal projects), and I'm not sure how to debug this, especially when I do not have a reproducible system.

**Comment by Temu4** [comment]
@paambaati Catch the same issue

![Screenshot 2023-03-08 at 1 28 56 PM](https://user-images.githubusercontent.com/42999342/223803759-a7aa8684-66bb-4b69-84b9-0eabbe39f16b.png)

**Comment by Temu4** [comment]
*UPD:*
Reran all checks it passed. 
Weird.

**Comment by paambaati** [comment]
I’m fairly confident that this is (was?) an issue on the GitHub side of things (as I’m seeing similar reports on other projects as well), hence the “external” label.

I’ll wait for @marcospassos to confirm before closing this issue.

**Comment by marcospassos** [comment]
I'm still facing the same issue in 100+ repositories. No other actions were affected, only the codeclimate-action.

**Comment by apge-jonathan** [comment]
We are seeing a similar issue in all of our installs as well, we had to add a step to download the key from the key server prior to kicking off the action

`- run: gpg --keyserver hkp://keys.openpgp.org --recv-keys 9BD9E2DD46DA965A537E5B0A5CBF320243B6FD85`

**Comment by paambaati** [comment]
@apge-jonathan Interesting. Would you mind answering a few questions —

1. did that step fix this issue completely?
2. What key is it?
3. Where did you find this key?
4. How did you arrive at this fix?

**Comment by marcospassos** [comment]
Yes, we're still facing this. This workaround worked for us: 

```yml
steps:
      - name: Change owner of container working directory
        run: chown root:root .
```
