### ISSUE TITLE
Allow `coverageCommand` to be a multiline script?

### ISSUE THREAD

**Issue by takanuva15** [paambaati/codeclimate-action#728]
**Is your feature request related to a problem? Please describe.**
I tried using this action with a multiline coverage command like so:
```
    - name: Generate and Publish CodeClimate report
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ env.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: |
          go test -cover -coverpkg=./... -coverprofile=c.out ./test/...
          cat c.out | grep -Fv "/test/" > c.tmp && mv c.tmp c.out               # remove /test/ coverage results
```
And it failed because I assume it's expecting only a single line.

Is there a way to allow it to accept a multiline bash script for generating the coverage report?

**Describe the solution you'd like**
Allow coverageCommand to be a multiline script.

**Describe alternatives you've considered**
Seems I have to split it into two separate steps currently since I can't do a multiline script for the coverage command

**Additional context**
N/A
